feat: add google operational info endpoint
immuni-app/immuni-backend-analytics pull request #17
Opened 2020-06-10 10:50 UTC by alessandroberlati

## Description

Add the operational info endpoint for the android clients

## Checklist

- [x] I have followed the indications in the [CONTRIBUTING](https://github.com/immuni-app/immuni-backend-analytics/blob/master/CONTRIBUTING.md).
- [ ] The documentation related to the proposed change has been updated accordingly (plus comments in code).
- [ ] I have written new tests for my core changes, as applicable.
- [ ] I have successfully run tests with my changes locally.
- [ ] It is ready for review! :rocket:

2020-06-10 13:21 UTC, alessandroberlati commented on immuni_analytics/apis/analytics.py
> +)
Eventually move to common

2020-06-10 14:30 UTC, ocardia requested changes
I left some comments, many are quite picky. I'd be glad to help you fix most of them. 🎉

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    "Check if the safety_net_payload is genuine and save the operational/info in the database."
This seems outdated when compared to the code. Also, typo in operational/info (`-` maybe)?

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +@doc.consumes(HeaderImmuniContentTypeJson(), location="header", required=True)
I'd keep headers first, body after (which is Swagger, for decorators order, would look exactly the opposite).

Also, I see a `location=header` and `location=headers`: one should be wrong.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    salt=fields.String(required=True),
Salt is made of random bytes only, it's not base64 or anything, right?

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    safety_net_payload: str,
Isn't it `signed_attestation`?

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    Check if the safety_net payload is valid and the salt has not been used
Check `safety_net_payload` vs `signed_attestation`

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +            "Previously used salt found for operational_info request.",
What about `Found previously used salt.` only? The log already brings the information of the file/function/line/etc.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +            extra=dict(payload=safety_net_payload, salt=salt),
When logging, I'd keep keys with the same name of the variables, making debugging an easier task due to the 1:1 mapping. 🙏

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: A redis key containing the salt
`A` -> `the`, since given a salt, there's only one key.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :param salt: the salt related to a request
Mmh, I think `corresponding to` is more appropriate.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    """Raised when one of the steps in the verification fails"""
Missing trailing `.`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    """
Missing `:param:` and `:return:`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    return f"~safetynet_used_salt:{salt}"
_minor_: I can't find it, but I remember a redis BKM about using `-` instead of `_` in key names.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    return jws_token.split(".")[index]
Maybe we could/should verify the length of the split is then actually three.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: the jws_token part specified by index
Missing trailing dots.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +def _safe_base64_decode(data: str) -> Dict[str, Any]:
I'd rename it to `_base64_pad_and_decode` to be more explicit.

Coherently, I'd rewrite the docstring as `Decode the given base64 string, adding padding if necessary`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: the decoded string
Missing trailing `.`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: the decoded string
`the base string to b64decode` -> `the base64 string to decode.`?

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    Returns the header of a jws token.
Consistency with other docstrings: `Return` instead of `Returns`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: The jws token header
Missing trailing `.`.
Also, `The` -> `the`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: The jws token payload
Same as above.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    """
Missing trailing `.`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :return: the leaf certificate
Missing trailing `.`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :param leaf_certificate: the leaf certificate extracted from the jws header
Missing trailing `.`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    :param salt: the salt sent in the request
Missing trailing `.`.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    # TODO apkCertificateDigestSha256
If you ain't addressing this TODO in this PR, I'd added a slightly more extensive comment.
TBH, I didn't exactly get what it to be done. 🙏

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +        _LOGGER.warning("The jws payload did not pass the validation check.")
I'd add `, extra=dict(payload=payload, lower_bound_skew=lower_bound_skew, upper_bound_skew= upper_bound_skew)`

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    payload: Dict[str, Any], operational_info: OperationalInfo, salt: str
Within this file, I'd stick to a single variable name for the payload, for which I now see at least `payload` and `safety_net_payload`. 🙏

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +        _LOGGER.warning("Could not verify jws signature", extra={"error": str(exc)})
Missing trailing `.` in message.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +        _LOGGER.warning("Could not retrieve header from jws token.", extra={"error": str(exc)})
Aren't all these logs `error`? 🤔

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +        _LOGGER.warning("Could not retrieve header from jws token.", extra={"error": str(exc)})
Also, we should probably log the payload in the extra so as to allow reproducibility or further investigation of an error. This assumes there's nothing sensible in the payload.

2020-06-10 14:30 UTC, ocardia commented on immuni_analytics/models/swagger.py
> +class GoogleOperationalInfo:
I'd rename the OperationalInfo as AppleOperationalInfo for consistency. What do you think?

Also, at least for the documentation, could it make sense to have a base class with the common information?

2020-06-10 14:30 UTC, ocardia commented on pyproject.toml
> +certvalidator = "^0.11.1"
I'd keep the alphabetical order.

Also, it may be worth pinning the versions as it has been done in common, for maximum reproducibility. Dependencies update will then be planned and explicit.

2020-06-10 14:34 UTC, alessandroberlati commented on immuni_analytics/apis/analytics.py
> +    salt=fields.String(required=True),
Correct

2020-06-10 14:35 UTC, alessandroberlati commented on immuni_analytics/apis/analytics.py
> +    safety_net_payload: str,
Sure, I refactored the validation only

2020-06-10 14:37 UTC, alessandroberlati commented on immuni_analytics/apis/analytics.py
> +    """
Do we actually need the params here? Since it is an API call the swagger should be enough (PyCharm does not complain for this reason)

2020-06-10 14:38 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +    return f"~safetynet_used_salt:{salt}"
~ shoud be for temporary keys

2020-06-10 14:40 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +    Returns the header of a jws token.
Maybe we should avoid Return(s) at all in the descriptions, what do you think?

2020-06-10 14:43 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +    payload: Dict[str, Any], operational_info: OperationalInfo, salt: str
I would use safety_net_attestation in the entrypoint method. Then Payload to be more generic (it is a jws after all)

2020-06-10 14:48 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    salt=fields.String(required=True),
🔝

2020-06-10 14:49 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    """
I'd double-check the other endpoints. I'd agree with you, if not that I got an OCD for consistency. 😓

2020-06-10 14:50 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    return f"~safetynet_used_salt:{salt}"
Yes, I meant `~safetynet-used-salt` instead of `~safetynet_used_salt`.

2020-06-10 14:53 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +    return f"~safetynet_used_salt:{salt}"
My bad :D `Dots or dashes are often used for multi-word fields, as in "comment:1234:reply.to" or "comment:1234:reply-to".` from https://redis.io/topics/data-types-intro.

Let's change it then

2020-06-10 14:54 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +def _safe_base64_decode(data: str) -> Dict[str, Any]:
I'd rather do a method to pad than a method with an and :D maybe we should?

2020-06-10 14:55 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +        _LOGGER.warning("Could not retrieve header from jws token.", extra={"error": str(exc)})
They could be errors as well as attacks.

2020-06-11 08:04 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +
I was wondering, should we add the `@slow_down` decorator used in ingestion (or something similar)?

2020-06-11 08:04 UTC, ocardia commented on immuni_analytics/helpers/safety_net.py
> +    return json.loads(base64.b64decode(jws_part).decode())
```suggestion
    missing_padding = "=" * ((4 - len(jws_part) % 4) % 4)
    padded_jws_part = f"{jws_part}{missing_padding}"
    return json.loads(base64.b64decode(padded_jws_part).decode())
```

2020-06-11 08:04 UTC, ocardia commented on pyproject.toml
> +freezegun = "==0.3.15"
This is already in the common/dev dependencies, AFAIK.

2020-06-11 09:04 UTC, alessandroberlati commented on immuni_analytics/helpers/safety_net.py
> +    return json.loads(base64.b64decode(jws_part).decode())
There's a useless %4 but I changed it. Thanks!

2020-06-11 15:39 UTC, ocardia commented on immuni_analytics/apis/analytics.py
> +    # this salt cannot be used for the next SAFETY_NET_MAX_SKEW_MINUTES
Should we check it wasn't set already?

2020-06-12 07:44 UTC, xelhark commented on immuni_analytics/apis/analytics.py
> +
For dummy requests yeah, it might make sense. I wouldn't use the decorator though, or you'd slow down ALL requests, not just dummy ones.

2020-06-12 07:44 UTC, xelhark commented on immuni_analytics/apis/analytics.py
> +    return json_response(body=None, status=HTTPStatus.NO_CONTENT)
Can we rewrite this as:

```
if not is_dummy:
     authorize..
return ...
```

2020-06-12 07:44 UTC, xelhark commented on immuni_analytics/apis/analytics.py
>          return json_response(body=None, status=HTTPStatus.NO_CONTENT)
We should probably add a delay here

2020-06-12 08:23 UTC, alessandroberlati commented on immuni_analytics/apis/analytics.py
> +    return json_response(body=None, status=HTTPStatus.NO_CONTENT)
This implementation is related to apple and will change as specified in the :return: docstring

2020-06-12 08:30 UTC, merged